from __future__ import annotations

from datetime import UTC, datetime, timedelta

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models import Assessment, Asset, Client, Contact, Finding, ScopeRecord, Site


def load_sample_data(db: Session) -> dict[str, int | str]:
    existing = db.scalar(select(Client).where(Client.domain == "northstar.example.com"))
    if existing:
        asset_count = len(db.scalars(select(Asset).where(Asset.client_id == existing.id)).all())
        finding_count = len(
            db.scalars(select(Finding).where(Finding.client_id == existing.id)).all()
        )
        return {
            "status": "already_loaded",
            "clients": 2,
            "sites": 3,
            "assets": asset_count,
            "findings": finding_count,
        }

    now = datetime.now(UTC).replace(tzinfo=None)
    client_a = Client(
        name="Northstar Example Manufacturing",
        legal_name="Northstar Example Manufacturing LLC",
        domain="northstar.example.com",
        status="Sample",
    )
    client_b = Client(
        name="Bluepine Example Services",
        legal_name="Bluepine Example Services LLC",
        domain="bluepine.example.com",
        status="Sample",
    )
    db.add_all([client_a, client_b])
    db.flush()

    sites = [
        Site(client_id=client_a.id, name="Northstar HQ", address="100 Example Way"),
        Site(client_id=client_a.id, name="Northstar Warehouse", address="200 Sample Loop"),
        Site(client_id=client_b.id, name="Bluepine Office", address="300 Demo Street"),
    ]
    db.add_all(sites)
    db.flush()

    db.add_all(
        [
            Contact(
                client_id=client_a.id,
                name="Primary Contact Example",
                email="primary.contact@northstar.example.com",
                role="Client sponsor",
            ),
            Contact(
                client_id=client_b.id,
                name="Operations Contact Example",
                email="operations.contact@bluepine.example.com",
                role="Operations sponsor",
            ),
        ]
    )

    assess_a = Assessment(
        client_id=client_a.id,
        name="Sample onboarding assessment",
        purpose="Onboarding",
        status="Sample",
    )
    assess_b = Assessment(
        client_id=client_b.id,
        name="Sample quarterly review",
        purpose="Quarterly Review",
        status="Sample",
    )
    db.add_all([assess_a, assess_b])
    db.flush()

    db.add_all(
        [
            ScopeRecord(
                assessment_id=assess_a.id,
                client_name=client_a.name,
                authorized_cidrs=["192.168.20.0/24", "192.168.21.0/24"],
                authorized_domains=["northstar.example.com"],
                start_time=now - timedelta(days=2),
                requested_by="Primary Contact Example",
                operator_notes="Sample data only. Not a live scan.",
            ),
            ScopeRecord(
                assessment_id=assess_b.id,
                client_name=client_b.name,
                authorized_cidrs=["10.50.4.0/24"],
                authorized_domains=["bluepine.example.com"],
                start_time=now - timedelta(days=1),
                requested_by="Operations Contact Example",
                operator_notes="Sample data only. Not a live scan.",
            ),
        ]
    )

    asset_specs = [
        (
            "ns-dc01",
            "192.168.20.10",
            "Windows",
            "Server 2012 R2",
            sites[0],
            assess_a,
            "Critical",
            None,
            [445, 3389],
            "missing",
            92,
            "healthy",
            True,
        ),
        (
            "ns-file01",
            "192.168.20.12",
            "Windows",
            "Server 2019",
            sites[0],
            assess_a,
            "Critical",
            "Finance Example",
            [445],
            "covered",
            86,
            "healthy",
            False,
        ),
        (
            "ns-app01",
            "192.168.20.20",
            "Linux",
            "Ubuntu 18.04",
            sites[0],
            assess_a,
            "High",
            "Apps Example",
            [22, 5432],
            "covered",
            74,
            "healthy",
            True,
        ),
        (
            "ns-wks-001",
            "192.168.20.101",
            "Windows",
            "11 Pro",
            sites[0],
            assess_a,
            "Medium",
            "User Example 001",
            [],
            "covered",
            62,
            "healthy",
            False,
        ),
        (
            "ns-wks-002",
            "192.168.20.102",
            "Windows",
            "10 Pro",
            sites[0],
            assess_a,
            "Medium",
            "User Example 002",
            [445],
            "unknown",
            None,
            "unknown",
            False,
        ),
        (
            "ns-wks-003",
            "192.168.20.103",
            "Windows",
            "7 Pro",
            sites[0],
            assess_a,
            "Low",
            None,
            [],
            None,
            None,
            None,
            True,
        ),
        (
            "ns-wks-004",
            "192.168.20.104",
            "Windows",
            "10 Pro",
            sites[0],
            assess_a,
            "Medium",
            "User Example 004",
            [],
            "covered",
            55,
            "healthy",
            False,
        ),
        (
            "ns-prn-01",
            "192.168.20.150",
            None,
            None,
            sites[0],
            assess_a,
            "Low",
            None,
            [9100],
            None,
            None,
            None,
            None,
        ),
        (
            "ns-wh-tablet-01",
            "192.168.21.40",
            "Android",
            "13",
            sites[1],
            assess_a,
            "Medium",
            "Warehouse Example",
            [],
            "not_reported",
            None,
            "not_reported",
            False,
        ),
        (
            "ns-wh-scan-01",
            "192.168.21.41",
            None,
            None,
            sites[1],
            assess_a,
            "Medium",
            None,
            [],
            None,
            None,
            None,
            None,
        ),
        (
            "bp-fw01",
            "10.50.4.1",
            "Network",
            "FirewallOS 3 Example",
            sites[2],
            assess_b,
            "Critical",
            "Network Example",
            [443],
            "not_applicable",
            None,
            "not_applicable",
            False,
        ),
        (
            "bp-nas01",
            "10.50.4.12",
            "Linux",
            "Debian 10",
            sites[2],
            assess_b,
            "Critical",
            None,
            [22, 445],
            "covered",
            91,
            "unknown",
            True,
        ),
        (
            "bp-sql01",
            "10.50.4.20",
            "Windows",
            "Server 2019",
            sites[2],
            assess_b,
            "High",
            "Data Example",
            [1433],
            "covered",
            79,
            "healthy",
            False,
        ),
        (
            "bp-wks-001",
            "10.50.4.101",
            "Windows",
            "11 Pro",
            sites[2],
            assess_b,
            "Medium",
            "User Example 101",
            [],
            "covered",
            48,
            "healthy",
            False,
        ),
        (
            "bp-wks-002",
            "10.50.4.102",
            "Windows",
            "10 Pro",
            sites[2],
            assess_b,
            "Medium",
            None,
            [],
            "missing",
            None,
            "missing",
            False,
        ),
        (
            "bp-wks-003",
            "10.50.4.103",
            "Windows",
            "10 Pro",
            sites[2],
            assess_b,
            "Low",
            "User Example 103",
            [],
            "covered",
            52,
            "healthy",
            False,
        ),
        (
            "bp-wks-004",
            "10.50.4.104",
            "Windows",
            "8.1",
            sites[2],
            assess_b,
            "Low",
            "User Example 104",
            [],
            None,
            None,
            None,
            True,
        ),
        (
            "bp-wks-005",
            "10.50.4.105",
            "Windows",
            "11 Pro",
            sites[2],
            assess_b,
            "Medium",
            "User Example 105",
            [],
            "covered",
            64,
            "healthy",
            False,
        ),
        (
            "bp-iot-01",
            "10.50.4.180",
            None,
            None,
            sites[2],
            assess_b,
            "Low",
            None,
            [80],
            None,
            None,
            None,
            None,
        ),
        (
            "bp-archive01",
            "10.50.4.40",
            "Linux",
            "Ubuntu 22.04",
            sites[2],
            assess_b,
            "Medium",
            "Records Example",
            [22],
            "covered",
            82,
            "healthy",
            False,
        ),
    ]

    assets: list[Asset] = []
    for index, spec in enumerate(asset_specs):
        (
            hostname,
            ip_address,
            os_family,
            os_version,
            site,
            assessment,
            criticality,
            owner,
            open_ports,
            backup_status,
            backup_storage_usage_percent,
            endpoint_security_status,
            unsupported_os,
        ) = spec
        asset = Asset(
            client_id=assessment.client_id,
            site_id=site.id,
            assessment_id=assessment.id,
            hostname=hostname,
            ip_address=ip_address,
            mac_address=f"02:00:00:00:{index // 255:02x}:{index % 255:02x}",
            os_family=os_family,
            os_version=os_version,
            last_seen=now - timedelta(days=45 if hostname.endswith("003") else index % 11),
            source="sample_import",
            tags=["sample", "lab"],
            criticality=criticality,
            owner=owner,
            metadata_json={
                "open_ports": open_ports,
                "backup_status": backup_status,
                "backup_storage_usage_percent": backup_storage_usage_percent,
                "endpoint_security_status": endpoint_security_status,
                "unsupported_os": unsupported_os,
                "restore_readiness_notes": "Sample restore evidence placeholder.",
            },
        )
        assets.append(asset)
    db.add_all(assets)
    db.flush()

    finding_specs = [
        (assess_a, "Critical asset without backup evidence", "Critical", "Backup", [assets[0]]),
        (assess_a, "Backup storage over 90 percent used", "High", "Backup", [assets[0]]),
        (assess_a, "Unsupported Windows OS detected", "High", "Patch", [assets[0], assets[5]]),
        (assess_a, "Host has exposed RDP", "High", "Network", [assets[0]]),
        (assess_a, "Host has exposed database service", "High", "Network", [assets[2]]),
        (assess_a, "Unsupported Linux distribution/version detected", "High", "Patch", [assets[2]]),
        (
            assess_a,
            "No endpoint backup status reported",
            "Medium",
            "Backup",
            [assets[4], assets[5], assets[8], assets[9]],
        ),
        (
            assess_a,
            "No endpoint security/AV/EDR status reported",
            "Medium",
            "Endpoint Security",
            [assets[4], assets[5], assets[8], assets[9]],
        ),
        (assess_a, "Host has exposed SMB", "Medium", "Network", [assets[0], assets[1], assets[4]]),
        (assess_a, "Backup storage over 80 percent used", "Medium", "Backup", [assets[1]]),
        (assess_a, "Unknown device detected", "Low", "Inventory", [assets[7], assets[9]]),
        (assess_a, "Device not seen in more than 30 days", "Low", "Operational Risk", [assets[5]]),
        (
            assess_a,
            "Missing asset owner",
            "Low",
            "Inventory",
            [assets[0], assets[5], assets[7], assets[9]],
        ),
        (assess_b, "Backup storage over 90 percent used", "High", "Backup", [assets[11]]),
        (
            assess_b,
            "Unsupported Linux distribution/version detected",
            "High",
            "Patch",
            [assets[11]],
        ),
        (assess_b, "Host has exposed database service", "High", "Network", [assets[12]]),
        (assess_b, "Unsupported Windows OS detected", "High", "Patch", [assets[16]]),
        (assess_b, "Critical asset without backup evidence", "Critical", "Backup", [assets[10]]),
        (assess_b, "Host has exposed SMB", "Medium", "Network", [assets[11]]),
        (
            assess_b,
            "No endpoint backup status reported",
            "Medium",
            "Backup",
            [assets[14], assets[16], assets[18]],
        ),
        (
            assess_b,
            "No endpoint security/AV/EDR status reported",
            "Medium",
            "Endpoint Security",
            [assets[11], assets[14], assets[16], assets[18]],
        ),
        (assess_b, "Unknown device detected", "Low", "Inventory", [assets[18]]),
        (assess_b, "Missing asset owner", "Low", "Inventory", [assets[11], assets[14], assets[18]]),
        (assess_b, "Backup storage over 80 percent used", "Medium", "Backup", [assets[19]]),
        (
            assess_b,
            "Patch compliance summary needs source evidence",
            "Informational",
            "Compliance Evidence",
            [assets[13], assets[15], assets[17]],
        ),
    ]
    for assessment, title, severity, category, affected_assets in finding_specs:
        finding = Finding(
            assessment_id=assessment.id,
            client_id=assessment.client_id,
            title=title,
            severity=severity,
            category=category,
            description=f"Sample finding for {title.lower()}.",
            evidence="Sample evidence generated from fake lab data. Not a live scan result.",
            impact="This risk indicator should be validated before remediation planning.",
            recommended_remediation="Validate the evidence, assign an owner, and track remediation through the client action plan.",
            status="Open",
            source="sample_data",
            confidence_score=0.72,
            metadata_json={"sample": True},
        )
        finding.assets = affected_assets
        db.add(finding)

    db.flush()
    return {"status": "loaded", "clients": 2, "sites": 3, "assets": 20, "findings": 25}
